### 일반 사용자 회원 가입 API
POST http://localhost:19091/api/auth/sign-up
Content-Type: application/json

{
  "username": "user2",
  "password": "password2",
  "slackId": "lingu2",
  "master": false,
  "masterToken": ""
}

### 마스터 관리자 회원 가입 API
POST http://localhost:19091/api/auth/sign-up
Content-Type: application/json

{
  "username": "master",
  "password": "password",
  "slackId": "master",
  "master": true,
  "masterToken": "MASTER_TOKEN_AI_B2B_THREE_III"
}

### 일반 사용자 로그인 API
POST http://localhost:19091/api/auth/sign-in
Content-Type: application/json

{
  "username": "user",
  "password": "password"
}
> {%
  client.global.set("token", response.headers.valueOf("Authorization"))
%}

### 마스터 로그인 API
POST http://localhost:19091/api/auth/sign-in
Content-Type: application/json

{
  "username": "master",
  "password": "password"
}
> {%
  client.global.set("token", response.headers.valueOf("Authorization"))
%}

### GW 테스트
GET http://localhost:19091/api/auth/test
Authorization: {{token}}
