server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - Authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
              - X-User-Name
            exposedHeaders:
              - x-requested-with
              - Authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
              - X-User-Name
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
      routes:
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
        - id: hub
          uri: lb://hub-service
          predicates:
            - Path=/api/hubs/**, /api/hub-paths/**
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/api/shippers/**
        - id: company
          uri: lb://company
          predicates:
            - Path=/api/companies/**, /api/products/**
        - id: slack
          uri: lb://slack-service
          predicates:
            - Path=/api/slack-messages/**
        - id: order
          uri: lb://orders
          predicates:
            - Path=/api/orders/**, /api/shippings/**, /api/shipping-paths/**
      discovery:
        locator:
          enabled: true
  security:
    csrf:
      enabled: false  # CSRF 비활성화

jwt:
  audience: b2b-client
  expiration-minutes: 30
  secret-key: local-three-iii-authenticate-secret-key

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

springdoc:
  swagger-ui:
    enabled: true
    use-root-path: true
    #    path: /swagger-ui.html
    #    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /api/auth/v3/api-docs
        name: auth
      - url: /api/hubs/v3/api-docs
        name: hub
      - url: /api/companies/v3/api-docs
        name: company
      - url: /api/orders/v3/api-docs
        name: order
      - url: /api/slack-messages/v3/api-docs
        name: slack
  api-docs:
    enabled: true
