spring:
  application:
    name: hub
  datasource:
    url: jdbc:postgresql://localhost:5432/b2b
    username: postgres
    password: qwer
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        highlight_sql: true
    defer-datasource-initialization: true #ddl-auto ?? ?? data.sql ??
  sql:
    init:
      mode: never #?? ????? always

server:
  port: 19093
  swagger:
    host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace

gemini:
  api:
    url: https://generativelanguage.googleapis.com
    key: ${GEMINI_KEY}

springdoc:
  api-docs:
    path: /api/hubs/v3/api-docs
  swagger-ui:
    path: /api/hubs/swagger-ui.html
