INSERT INTO p_hub (id, name, address, latitude, longitude, phone_number, is_delete, created_at,
                   updated_at)
VALUES (uuid_generate_v4(), '서울특별시 센터', '서울특별시 송파구 송파대로 55', '37.5146', '127.1122', '02-1234-5678',
        false, now(), now()),
       (uuid_generate_v4(), '경기 북부 센터', '경기도 고양시 덕양구 권율대로 570', '37.6500', '126.8662',
        '031-1234-5678', false, now(), now()),
       (uuid_generate_v4(), '경기 남부 센터', '경기도 이천시 덕평로 257-21', '37.2799', '127.4411',
        '031-2345-6789', false, now(), now()),
       (uuid_generate_v4(), '부산광역시 센터', '부산 동구 중앙대로 206', '35.1330', '129.0598', '051-1234-5678',
        false, now(), now()),
       (uuid_generate_v4(), '대구광역시 센터', '대구 북구 태평로 161', '35.8856', '128.5820', '053-1234-5678',
        false, now(), now()),
       (uuid_generate_v4(), '인천광역시 센터', '인천 남동구 정각로 29', '37.4476', '126.7317', '032-1234-5678',
        false, now(), now()),
       (uuid_generate_v4(), '광주광역시 센터', '광주 서구 내방로 111', '35.1595', '126.8514', '062-1234-5678',
        false, now(), now()),
       (uuid_generate_v4(), '대전광역시 센터', '대전 서구 둔산로 100', '36.3510', '127.3780', '042-1234-5678',
        false, now(), now()),
       (uuid_generate_v4(), '울산광역시 센터', '울산 남구 중앙로 201', '35.5384', '129.3114', '052-1234-5678',
        false, now(), now()),
       (uuid_generate_v4(), '세종특별자치시 센터', '세종특별자치시 한누리대로 2130', '36.4800', '127.2890',
        '044-1234-5678', false, now(), now()),
       (uuid_generate_v4(), '강원특별자치도 센터', '강원특별자치도 춘천시 중앙로 1', '37.8813', '127.7298',
        '033-1234-5678', false, now(), now()),
       (uuid_generate_v4(), '충청북도 센터', '충북 청주시 상당구 상당로 82', '36.6357', '127.4911', '043-1234-5678',
        false, now(), now()),
       (uuid_generate_v4(), '충청남도 센터', '충남 홍성군 홍북읍 충남대로 21', '36.6011', '126.6625', '041-1234-5678',
        false, now(), now()),
       (uuid_generate_v4(), '전북특별자치도 센터', '전북특별자치도 전주시 완산구 효자로 225', '35.8242', '127.1470',
        '063-1234-5678',
        false, now(), now()),
       (uuid_generate_v4(), '전라남도 센터', '전남 무안군 삼향읍 오룡길 1', '34.9917', '126.4947', '061-1234-5678',
        false, now(), now()),
       (uuid_generate_v4(), '경상북도 센터', '경북 안동시 풍천면 도청대로 455', '36.5684', '128.7296',
        '054-1234-5678', false, now(), now()),
       (uuid_generate_v4(), '경상남도 센터', '경남 창원시 의창구 중앙대로 300', '35.2342', '128.6811',
        '055-1234-5678', false, now(), now());

INSERT INTO p_hub_path (id, departure_id, arrivals_id, time_required, name, is_delete, created_at,
                        updated_at)
VALUES (uuid_generate_v4(), (SELECT id FROM p_hub WHERE name = '서울특별시 센터'),
        (SELECT id FROM p_hub WHERE name = '경기 북부 센터'), '2시간', '서울 -> 경기 북부', false, now(), now()),
       (uuid_generate_v4(), (SELECT id FROM p_hub WHERE name = '경기 북부 센터'),
        (SELECT id FROM p_hub WHERE name = '경기 남부 센터'), '1시간 30분', '경기 북부 -> 경기 남부', false, now(),
        now()),
       (uuid_generate_v4(), (SELECT id FROM p_hub WHERE name = '경기 남부 센터'),
        (SELECT id FROM p_hub WHERE name = '부산광역시 센터'), '4시간', '경기 남부 -> 부산', false, now(), now()),
       (uuid_generate_v4(), (SELECT id FROM p_hub WHERE name = '부산광역시 센터'),
        (SELECT id FROM p_hub WHERE name = '대구광역시 센터'), '2시간', '부산 -> 대구', false, now(), now()),
       (uuid_generate_v4(), (SELECT id FROM p_hub WHERE name = '대구광역시 센터'),
        (SELECT id FROM p_hub WHERE name = '인천광역시 센터'), '3시간', '대구 -> 인천', false, now(), now()),
       (uuid_generate_v4(), (SELECT id FROM p_hub WHERE name = '인천광역시 센터'),
        (SELECT id FROM p_hub WHERE name = '광주광역시 센터'), '3시간 30분', '인천 -> 광주', false, now(), now()),
       (uuid_generate_v4(), (SELECT id FROM p_hub WHERE name = '광주광역시 센터'),
        (SELECT id FROM p_hub WHERE name = '대전광역시 센터'), '2시간', '광주 -> 대전', false, now(), now()),
       (uuid_generate_v4(), (SELECT id FROM p_hub WHERE name = '대전광역시 센터'),
        (SELECT id FROM p_hub WHERE name = '울산광역시 센터'), '3시간', '대전 -> 울산', false, now(), now()),
       (uuid_generate_v4(), (SELECT id FROM p_hub WHERE name = '울산광역시 센터'),
        (SELECT id FROM p_hub WHERE name = '세종특별자치시 센터'), '3시간 30분', '울산 -> 세종', false, now(),
        now()),
       (uuid_generate_v4(), (SELECT id FROM p_hub WHERE name = '세종특별자치시 센터'),
        (SELECT id FROM p_hub WHERE name = '강원특별자치도 센터'), '4시간', '세종 -> 강원', false, now(), now()),
       (uuid_generate_v4(), (SELECT id FROM p_hub WHERE name = '강원특별자치도 센터'),
        (SELECT id FROM p_hub WHERE name = '충청북도 센터'), '1시간 30분', '강원 -> 충북', false, now(), now()),
       (uuid_generate_v4(), (SELECT id FROM p_hub WHERE name = '충청북도 센터'),
        (SELECT id FROM p_hub WHERE name = '충청남도 센터'), '1시간', '충북 -> 충남', false, now(), now()),
       (uuid_generate_v4(), (SELECT id FROM p_hub WHERE name = '충청남도 센터'),
        (SELECT id FROM p_hub WHERE name = '전북특별자치도 센터'), '2시간', '충남 -> 전북', false, now(), now()),
       (uuid_generate_v4(), (SELECT id FROM p_hub WHERE name = '전북특별자치도 센터'),
        (SELECT id FROM p_hub WHERE name = '전라남도 센터'), '3시간', '전북 -> 전남', false, now(), now()),
       (uuid_generate_v4(), (SELECT id FROM p_hub WHERE name = '전라남도 센터'),
        (SELECT id FROM p_hub WHERE name = '경상북도 센터'), '4시간', '전남 -> 경북', false, now(), now()),
       (uuid_generate_v4(), (SELECT id FROM p_hub WHERE name = '경상북도 센터'),
        (SELECT id FROM p_hub WHERE name = '경상남도 센터'), '3시간 30분', '경북 -> 경남', false, now(), now());
