spring:
  application:
    name: eureka-server
server:
  port: 19090
eureka:
  client:
    # 유레카 서버에 자신을 등록할지 여부를 설정합니다.
    # true로 설정하면 유레카 클라이언트가 유레카 서버에 자신을 등록합니다.
    # 유레카 서버에서는 일반적으로 false로 설정하여, 서버가 자기 자신을 등록하지 않도록 합니다.
    register-with-eureka: false
    # 유레카 서버로부터 레지스트리를 가져올지 여부를 설정합니다.
    # true로 설정하면 유레카 클라이언트가 유레카 서버로부터 다른 서비스 인스턴스 목록을 가져옵니다.
    # 유레카 서버에서는 일반적으로 false로 설정하여, 레지스트리를 가져오지 않도록 합니다.
    fetch-registry: false
    # 유레카 클라이언트가 유레카 서버와 통신하기 위해 사용할 기본 서비스 URL을 설정합니다.
    # 클라이언트 애플리케이션이 유레카 서버에 연결하고 등록하거나 레지스트리를 가져올 때 사용할 URL을 지정합니다.
    service-url:
      defaultZone: http://localhost:19090/eureka/
  # 유레카 서버 인스턴스의 호스트 이름을 설정합니다.
  # 유레카 서버가 자신의 호스트 이름을 다른 서비스에 알릴 때 사용합니다.
  instance:
    hostname: localhost
