### 일반 사용자 회원 가입 API
POST http://localhost:19092/auth/sign-up
Content-Type: application/json

{
  "username": "user",
  "password": "password",
  "slackId": "lingu",
  "master": false,
  "masterToken": ""
}

### 마스터 관리자 회원 가입 API
POST http://localhost:19092/auth/sign-up
Content-Type: application/json

{
  "username": "master1",
  "password": "password",
  "slackId": "master1",
  "master": true,
  "masterToken": "MASTER_TOKEN_AI_B2B_THREE_III1"
}
